### PR TITLE
apply --paper-font-common-base

### PR DESCRIPTION
**Pull request by valdrinkoshi**
Applies `--paper-font-common-base` to the host.

This is part of the effort of applying `Roboto` font to all the paper elements http://jsbin.com/mumovix/1/edit?html,output

### CODE REVIEW

**Comment by valdrinkoshi** [comment]
@cdata @notwaldorf kindly review

**Comment by notwaldorf** [comment]
As talked offline, I think this PR should only apply the mixin, and not import the font.

**Comment by valdrinkoshi** [comment]
@notwaldorf PR updated :+1:

**Comment by notwaldorf** [comment]
Should this maybe just go in the `.toggle-label` since that's the only thing displaying text?

**Comment by valdrinkoshi** [comment]
As agreed offline, we leave it in the host for now, since it produces the same result.
Updated the docs.

**Comment by notwaldorf** [comment]
LGTM 💯

**Pull request merged**
