### PR TITLE
Remove unneeded paper-ripple import

### PR DESCRIPTION
**Pull request by abdonrd**
The `paper-behaviors/paper-checked-element-behavior.html` already import the `paper-ripple`.

### CODE REVIEW

**Comment by bicknellr** [comment]
I think we should keep this import since PaperRippleBehavior it's explicitly referenced.

**Comment by abdonrd** [comment]
@bicknellr the `paper-ripple.html` has not the `PaperRippleBehavior`.

The `PaperRippleBehavior` is in the:
- `paper-behaviors/paper-checked-element-behavior.html` >
- `paper-behaviors/paper-inky-focus-behavior.html` >
- `paper-ripple-behavior.html` > `PaperRippleBehavior`

**Comment by bicknellr** [comment]
Oh! Thanks for the correction; I was confusing paper-ripple and PaperRippleBehavior.

**Comment by abdonrd** [comment]
@bicknellr Nothing happens! You are welcome! :blush:

**Comment by bicknellr** [comment]
Oh, oops, I forgot to ask about the bower.json. I'll remove the dependency in another PR before tagging a release.

**Comment by abdonrd** [comment]
Oops! Your right! I forgot the `bower.json`.

**Pull request merged**
